### ISSUE TITLE
Verbose flag to show progress

### ISSUE THREAD

**Issue by buckhx** [invernizzi/vagrant-scp#10]
If I have a large file I am transferring there's no feedback for it's progress so I don't know if it's chugging along fine or hanging.

**Comment by invernizzi** [comment]
Thanks for noticing! The feedback was there until PR #8, which replaced the direct call to `scp` with a more elegant call to `Net::Ssh`. This commit brings back the feedback.
I've decided to set it as a default, without the verbose flag, because that's how `scp` does it. Let me know if you prefer a flag.

**Comment by buckhx** [comment]
makes sense to me!
