### ISSUE TITLE
latest version is very slow to copy files

### ISSUE THREAD

**Issue by rimusz** [invernizzi/vagrant-scp#11]
v0.5.3 is very slow even to copy small files, v0.4.1 was fine.
I'm using latest vagrant v1.7.4 and OSX 10.11

**Comment by invernizzi** [comment]
Thanks for reporting this, Rimas.
This has probably been caused by PR #8, which replaces the direct use of the `scp` executable with Net::SCP.
I tried to reproduce it on my laptop like so (i5 CPU, 8gb RAM):

``` bash
$ dd if=/dev/urandom of=file.out bs=1MB count=100  # 100 mb file.
$ vagrant plugin install --plugin-version 0.4.1  vagrant-scp
Installed the plugin 'vagrant-scp (0.4.1)'!
$ time vagrant scp file.out :test.out                       
1.89s user 0.52s system 26% cpu 9.190 total
 $ vagrant plugin install --plugin-version 0.5.3  vagrant-scp                                 
Installed the plugin 'vagrant-scp (0.5.3)'!
$ time vagrant scp file.out :test.out                       
6.83s user 0.44s system 77% cpu 9.431 total
```

It does take more CPU cycles (as the copy is being handled directly by Ruby), but the total time is fairly similar. Do you mind trying the same steps and reporting your results? If there is a noticeable performance issue, I'll revert to invoking scp directly.

**Comment by rimusz** [comment]
my test results for 35mb file:
v0.5.3

```
time vagrant scp kube.tgz k8solo-01:/home/core

kube.tgz: 100.0%%
real    2m52.821s
user    2m47.232s
sys 0m1.525s
99% CPU use
```

v0.4.1

```
time vagrant scp kube.tgz k8solo-01:/home/core
Warning: Permanently added '[127.0.0.1]:2222' (ED25519) to the list of known hosts.
kube.tgz                                                                                                                                           100%   35MB  34.6MB/s   00:01

real    0m2.988s
user    0m1.858s
sys 0m0.396s
```

**Comment by invernizzi** [comment]
Thanks for testing! I've reverted to calling scp directly, as Net:SCP is too slow.
Version 0.5.4 is fast again.
