### ISSUE TITLE
what is vm_name?

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [invernizzi/vagrant-scp#5]
Do I have to have the vm_name?

Do all plugins (vagrant-aws etc..) have this option?

what if I spinned a machine without a name, how can I get it?
I think it is completely relevant to make that optional. perhaps if I write `_:` - I expect you to figure it out yourself or something.  

I keep getting: The machine with the name 'aaa' was not found configured for
this Vagrant environment.

even though my vagrantfile states: 

 v.name = 'aaa'

**Comment by guy-mograbi-at-gigaspaces** [comment]
I was finally able to copy the file. 

In order to figure out the vm name I wrote 

`sudo vagrant global-status` (does not work properly without sudo)

and saw all names are `default` - as I am not using multiple machines in same Vagrantfile... 

I still think that `default` should be some kind of default.. (yes, I am aware)

and that if I wrote 

`vagrant scp :my-file .`

it should work.

**Comment by invernizzi** [comment]
Hi Guy,
thanks for the suggestion! I've updated the gem, so that

```
 vagrant scp :my-file .
```

works fine, and I've updated the Readme to reflect that. Version 0.4.2 has the fix.

The "The machine with the name 'aaa' was not found" issue is odd. The simplest explanation I can think of is that you set the name after booting the machine (and Vagrant doesn't support that).
