### ISSUE TITLE
Environment ID is required

### ISSUE THREAD

**Issue by DarylWM** [invernizzi/vagrant-scp#6]
Trying to use the plugin, but get this error:

$ vagrant scp /home/vagrant/test.txt ./
.../.vagrant.d/gems/gems/vagrant-scp-0.4.2/lib/vagrant/scp/commands/scp.rb:19:in `execute': undefined method`empty?' for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in`cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'

Adding the environment ID worked, but I thought it was optional if there is only one.

Vagrant version is 1.7.4.

**Comment by invernizzi** [comment]
Hi Daryl,
I've decided to disable that behaviour because it was confusing to some users, as the direction in which the scp happens (from the Vagrant VM to the local host, or vice versa) is unspecified.
You should be able to run that command as:

```
vagrant scp :/home/vagrant/test.txt ./
```

Where the ':' indicate the remote host. This is equivalent to:

```
vagrant scp default:/home/vagrant/test.txt ./
```

Let me know if it works out for you, because it's a brand new feature, that was added yesterday.
